apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-app
  namespace: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend-app

  template:
    metadata:
      labels:
        app: frontend-app

    spec:
      containers:
        - name: frontend-app

          image: sachin19102001/frontend-repo:1

          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXTAUTH_SECRET

            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXTAUTH_URL

            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: PORT