apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: frontend
type: Opaque
stringData:
  NEXTAUTH_SECRET: "4f2cfbbe5b1d601baf15932b3e7b857e8dd50f95ce5440f8dffc81822dfbe53a"
  NEXTAUTH_URL: "http://localhost:3005"
  PORT: "3005"
